### PR TITLE
confd.toml breaks with recent confd if there is a [confd] header

### PR DESCRIPTION
**Pull request by gozer**
This just removes the offending header from the config file template

### CODE REVIEW

**Comment by ajcrowe** [comment]
I think this needs some more work to make it a bit more OS agnostic.

**Comment by gozer** [comment]
OS agnostic? Do you mean by that the [confd] is required on some OSes ?

**Comment by ajcrowe** [comment]
Given this is a specific Upstart script, this would not work with RedHat, Debian etc. We would also not want to have this change existing users configurations. 

I think making installation optional and disabled by default. Then make the file resource something like 

```puppet
if $confd::init_install {
  file { "$confd::init_file":
    ensure  => present,
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template("confd/init.${::operatingsystem}.erb"),
  }
}
```

What do you think?

**Comment by gozer** [comment]
Oh, I see, my bad, this branch included unrelated fixes, apologies.

**Pull request closed without merging**
